# XXX 'program' might not be the best word, but neither is 'command'
BASHTUTOR_TASK_FILE_LIST+=(tasks/greeting.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/command.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/arguments_1.sh) # echo is learned
BASHTUTOR_TASK_FILE_LIST+=(tasks/arguments_2.sh) # touch is learned
BASHTUTOR_TASK_FILE_LIST+=(tasks/arguments_3.sh) # conditions hinted at
BASHTUTOR_TASK_FILE_LIST+=(tasks/help.sh)        # man/info mentioned
BASHTUTOR_TASK_FILE_LIST+=(tasks/program_types.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/variable_assignment.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/variable_expansion_and_splitting.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/variable_config.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/exit_statuses.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/conditional_execution.sh) # cat learned
BASHTUTOR_TASK_FILE_LIST+=(tasks/functions.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/redirections.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/glob.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/complex_expension_monk_task.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/logic.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/control.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/jobs.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/scripts.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/sourcing.sh)
BASHTUTOR_TASK_FILE_LIST+=(tasks/goodbye.sh)
