#!/bin/sh

[ $# -eq 0 ] && echo "bashtutor: no module name was provided, nothing to do." && exit 0

export PROMPT_COMMAND="source bashtutor_helper $1"
export HISTFILE=""
export PS1="(bashtutor) \\$ "
bash --norc --noprofile
